/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Marketplace {
  export type AuctionStruct = {
    author: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    highestBidder: PromiseOrValue<string>;
    highestBid: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type AuctionStructOutput = [
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    author: string;
    contractAddress: string;
    tokenId: BigNumber;
    highestBidder: string;
    highestBid: BigNumber;
    endTime: BigNumber;
    isActive: boolean;
  };

  export type AuctionOutputStruct = {
    auctionId: PromiseOrValue<BigNumberish>;
    author: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    tokenUri: PromiseOrValue<string>;
    highestBidder: PromiseOrValue<string>;
    highestBid: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type AuctionOutputStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    auctionId: BigNumber;
    author: string;
    contractAddress: string;
    tokenId: BigNumber;
    tokenUri: string;
    highestBidder: string;
    highestBid: BigNumber;
    endTime: BigNumber;
    isActive: boolean;
  };

  export type CollectionStruct = {
    author: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    title: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    totalItems: PromiseOrValue<BigNumberish>;
  };

  export type CollectionStructOutput = [
    string,
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    author: string;
    contractAddress: string;
    title: string;
    symbol: string;
    description: string;
    totalItems: BigNumber;
  };

  export type SaleStruct = {
    author: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
  };

  export type SaleStructOutput = [string, string, BigNumber, BigNumber] & {
    author: string;
    contractAddress: string;
    tokenId: BigNumber;
    price: BigNumber;
  };

  export type SaleOutputStruct = {
    saleId: PromiseOrValue<BigNumberish>;
    author: PromiseOrValue<string>;
    contractAddress: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    tokenUri: PromiseOrValue<string>;
  };

  export type SaleOutputStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    saleId: BigNumber;
    author: string;
    contractAddress: string;
    tokenId: BigNumber;
    price: BigNumber;
    tokenUri: string;
  };
}

export interface MarketplaceInterface extends utils.Interface {
  functions: {
    "auctionBid(uint256)": FunctionFragment;
    "auctionCount()": FunctionFragment;
    "auctionResolve(uint256)": FunctionFragment;
    "buySale(uint256)": FunctionFragment;
    "cancelSale(uint256)": FunctionFragment;
    "collectionCount()": FunctionFragment;
    "collectionImplementation()": FunctionFragment;
    "createAuction(address,uint256,uint256,uint256)": FunctionFragment;
    "createCollection(string,string,string,string,uint256,uint256)": FunctionFragment;
    "createSale(address,uint256,uint256)": FunctionFragment;
    "getAuctionById(uint256)": FunctionFragment;
    "getAuctions()": FunctionFragment;
    "getCollectionById(uint256)": FunctionFragment;
    "getCollections()": FunctionFragment;
    "getSaleById(uint256)": FunctionFragment;
    "getSales()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "saleCount()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "auctionBid"
      | "auctionCount"
      | "auctionResolve"
      | "buySale"
      | "cancelSale"
      | "collectionCount"
      | "collectionImplementation"
      | "createAuction"
      | "createCollection"
      | "createSale"
      | "getAuctionById"
      | "getAuctions"
      | "getCollectionById"
      | "getCollections"
      | "getSaleById"
      | "getSales"
      | "owner"
      | "renounceOwnership"
      | "saleCount"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "auctionBid",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctionResolve",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "buySale",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSale",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectionImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSale",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleById",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getSales", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "saleCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "auctionBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buySale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectionImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSales", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saleCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AuctionCreated(address,address,uint256,uint256)": EventFragment;
    "AuctionNewBid(address,address,uint256)": EventFragment;
    "AuctionResolved(address,uint256,address)": EventFragment;
    "CollectionCreated(address,address)": EventFragment;
    "CommissionReceivedByMarketplace(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SaleCanceled(address,address,uint256)": EventFragment;
    "SaleCreated(address,address,uint256,uint256)": EventFragment;
    "SaleSuccessed(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionNewBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionResolved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CommissionReceivedByMarketplace"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleSuccessed"): EventFragment;
}

export interface AuctionCreatedEventObject {
  author: string;
  contractAddress: string;
  tokenId: BigNumber;
  auctionId: BigNumber;
}
export type AuctionCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  AuctionCreatedEventObject
>;

export type AuctionCreatedEventFilter = TypedEventFilter<AuctionCreatedEvent>;

export interface AuctionNewBidEventObject {
  contractAddress: string;
  bidder: string;
  amount: BigNumber;
}
export type AuctionNewBidEvent = TypedEvent<
  [string, string, BigNumber],
  AuctionNewBidEventObject
>;

export type AuctionNewBidEventFilter = TypedEventFilter<AuctionNewBidEvent>;

export interface AuctionResolvedEventObject {
  contractAddress: string;
  tokenId: BigNumber;
  winner: string;
}
export type AuctionResolvedEvent = TypedEvent<
  [string, BigNumber, string],
  AuctionResolvedEventObject
>;

export type AuctionResolvedEventFilter = TypedEventFilter<AuctionResolvedEvent>;

export interface CollectionCreatedEventObject {
  author: string;
  contractAddress: string;
}
export type CollectionCreatedEvent = TypedEvent<
  [string, string],
  CollectionCreatedEventObject
>;

export type CollectionCreatedEventFilter =
  TypedEventFilter<CollectionCreatedEvent>;

export interface CommissionReceivedByMarketplaceEventObject {
  commission: BigNumber;
}
export type CommissionReceivedByMarketplaceEvent = TypedEvent<
  [BigNumber],
  CommissionReceivedByMarketplaceEventObject
>;

export type CommissionReceivedByMarketplaceEventFilter =
  TypedEventFilter<CommissionReceivedByMarketplaceEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SaleCanceledEventObject {
  author: string;
  contractAddress: string;
  tokenId: BigNumber;
}
export type SaleCanceledEvent = TypedEvent<
  [string, string, BigNumber],
  SaleCanceledEventObject
>;

export type SaleCanceledEventFilter = TypedEventFilter<SaleCanceledEvent>;

export interface SaleCreatedEventObject {
  author: string;
  contractAddress: string;
  tokenId: BigNumber;
  price: BigNumber;
}
export type SaleCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  SaleCreatedEventObject
>;

export type SaleCreatedEventFilter = TypedEventFilter<SaleCreatedEvent>;

export interface SaleSuccessedEventObject {
  newOwner: string;
  contractAddress: string;
  tokenId: BigNumber;
}
export type SaleSuccessedEvent = TypedEvent<
  [string, string, BigNumber],
  SaleSuccessedEventObject
>;

export type SaleSuccessedEventFilter = TypedEventFilter<SaleSuccessedEvent>;

export interface Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    auctionBid(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    auctionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    auctionResolve(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buySale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelSale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    collectionImplementation(overrides?: CallOverrides): Promise<[string]>;

    createAuction(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _startingBid: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCollection(
      _title: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createSale(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAuctionById(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.AuctionStructOutput]>;

    getAuctions(
      overrides?: CallOverrides
    ): Promise<[Marketplace.AuctionOutputStructOutput[]]>;

    getCollectionById(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.CollectionStructOutput]>;

    getCollections(
      overrides?: CallOverrides
    ): Promise<[Marketplace.CollectionStructOutput[]]>;

    getSaleById(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.SaleStructOutput]>;

    getSales(
      overrides?: CallOverrides
    ): Promise<[Marketplace.SaleOutputStructOutput[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    saleCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  auctionBid(
    _auctionId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  auctionCount(overrides?: CallOverrides): Promise<BigNumber>;

  auctionResolve(
    _auctionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buySale(
    _saleId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelSale(
    _saleId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

  collectionImplementation(overrides?: CallOverrides): Promise<string>;

  createAuction(
    _contractAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _startingBid: PromiseOrValue<BigNumberish>,
    _endTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCollection(
    _title: PromiseOrValue<string>,
    _symbol: PromiseOrValue<string>,
    _description: PromiseOrValue<string>,
    _uri: PromiseOrValue<string>,
    _price: PromiseOrValue<BigNumberish>,
    _supply: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createSale(
    _contractAddress: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAuctionById(
    _auctionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Marketplace.AuctionStructOutput>;

  getAuctions(
    overrides?: CallOverrides
  ): Promise<Marketplace.AuctionOutputStructOutput[]>;

  getCollectionById(
    _collectionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Marketplace.CollectionStructOutput>;

  getCollections(
    overrides?: CallOverrides
  ): Promise<Marketplace.CollectionStructOutput[]>;

  getSaleById(
    _saleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Marketplace.SaleStructOutput>;

  getSales(
    overrides?: CallOverrides
  ): Promise<Marketplace.SaleOutputStructOutput[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  saleCount(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    auctionBid(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    auctionCount(overrides?: CallOverrides): Promise<BigNumber>;

    auctionResolve(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buySale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelSale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

    collectionImplementation(overrides?: CallOverrides): Promise<string>;

    createAuction(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _startingBid: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createCollection(
      _title: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createSale(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAuctionById(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Marketplace.AuctionStructOutput>;

    getAuctions(
      overrides?: CallOverrides
    ): Promise<Marketplace.AuctionOutputStructOutput[]>;

    getCollectionById(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Marketplace.CollectionStructOutput>;

    getCollections(
      overrides?: CallOverrides
    ): Promise<Marketplace.CollectionStructOutput[]>;

    getSaleById(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Marketplace.SaleStructOutput>;

    getSales(
      overrides?: CallOverrides
    ): Promise<Marketplace.SaleOutputStructOutput[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    saleCount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AuctionCreated(address,address,uint256,uint256)"(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      auctionId?: null
    ): AuctionCreatedEventFilter;
    AuctionCreated(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      auctionId?: null
    ): AuctionCreatedEventFilter;

    "AuctionNewBid(address,address,uint256)"(
      contractAddress?: PromiseOrValue<string> | null,
      bidder?: PromiseOrValue<string> | null,
      amount?: null
    ): AuctionNewBidEventFilter;
    AuctionNewBid(
      contractAddress?: PromiseOrValue<string> | null,
      bidder?: PromiseOrValue<string> | null,
      amount?: null
    ): AuctionNewBidEventFilter;

    "AuctionResolved(address,uint256,address)"(
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      winner?: PromiseOrValue<string> | null
    ): AuctionResolvedEventFilter;
    AuctionResolved(
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      winner?: PromiseOrValue<string> | null
    ): AuctionResolvedEventFilter;

    "CollectionCreated(address,address)"(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null
    ): CollectionCreatedEventFilter;
    CollectionCreated(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null
    ): CollectionCreatedEventFilter;

    "CommissionReceivedByMarketplace(uint256)"(
      commission?: null
    ): CommissionReceivedByMarketplaceEventFilter;
    CommissionReceivedByMarketplace(
      commission?: null
    ): CommissionReceivedByMarketplaceEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "SaleCanceled(address,address,uint256)"(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): SaleCanceledEventFilter;
    SaleCanceled(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): SaleCanceledEventFilter;

    "SaleCreated(address,address,uint256,uint256)"(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      price?: null
    ): SaleCreatedEventFilter;
    SaleCreated(
      author?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      price?: null
    ): SaleCreatedEventFilter;

    "SaleSuccessed(address,address,uint256)"(
      newOwner?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): SaleSuccessedEventFilter;
    SaleSuccessed(
      newOwner?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): SaleSuccessedEventFilter;
  };

  estimateGas: {
    auctionBid(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    auctionCount(overrides?: CallOverrides): Promise<BigNumber>;

    auctionResolve(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buySale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelSale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectionCount(overrides?: CallOverrides): Promise<BigNumber>;

    collectionImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    createAuction(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _startingBid: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCollection(
      _title: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createSale(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAuctionById(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuctions(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionById(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollections(overrides?: CallOverrides): Promise<BigNumber>;

    getSaleById(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSales(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    saleCount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionBid(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    auctionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auctionResolve(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buySale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelSale(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collectionImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createAuction(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _startingBid: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCollection(
      _title: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _description: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createSale(
      _contractAddress: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAuctionById(
      _auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuctions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollectionById(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollections(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSaleById(
      _saleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSales(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    saleCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
