// Code generated by protoc-gen-js-fetch.
// DO NOT EDIT!

export interface Trait {
  trait_type?: string;
  value?: string;
}

export const Trait_traitType = "trait_type";
export const Trait_value = "value";
export interface Creator {
  address?: string;
  share?: number;
}

export const Creator_address = "address";
export const Creator_share = "share";
export interface MetadataFile {
  uri?: string;
  type?: string;
}

export const MetadataFile_uri = "uri";
export const MetadataFile_type = "type";
export interface MetadataProperties {
  category?: string;
  files?: MetadataFile[];
  creators?: Creator[];
}

export const MetadataProperties_category = "category";
export const MetadataProperties_files = "files";
export const MetadataProperties_creators = "creators";
export interface Metadata {
  name?: string;
  symbol?: string;
  external_url?: string;
  description?: string;
  seller_fee_basis_points?: number;
  collection?: string;
  image?: string;
  attributes?: Trait[];
  properties?: MetadataProperties;
}

export const Metadata_name = "name";
export const Metadata_symbol = "symbol";
export const Metadata_externalUrl = "external_url";
export const Metadata_description = "description";
export const Metadata_sellerFeeBasisPoints = "seller_fee_basis_points";
export const Metadata_collection = "collection";
export const Metadata_image = "image";
export const Metadata_attributes = "attributes";
export const Metadata_properties = "properties";
